FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.prod.txt ./
RUN python -m pip install --upgrade pip \
    && python -m pip install -r requirements.prod.txt

COPY . .

CMD ["python", "service.py"]

